title: Grav T2B5 Skeleton
author:
  name: Joe Bloggs
  email: 'joe@example.com'
metadata:
    description: 'T2B5 is a Boostrap 5 skeleton for Grav, an easy to use yet powerful, open source flat-file CMS'

