title: Grav T2B4 Skeleton
author:
  name: Joe Bloggs
  email: 'joe@example.com'
metadata:
    description: 'T2B4 is a Boostrap 4 skeleton for Grav, an easy to use yet powerful, open source flat-file CMS'

